# Generated by Django 3.2.11 on 2022-02-02 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_applicant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipCreation',
            fields=[
                ('application_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_applicant.application')),
                ('statement', models.FileField(upload_to='')),
                ('transcript', models.FileField(upload_to='')),
                ('recommendation_letter_1', models.FileField(upload_to='')),
                ('recommendation_letter_2', models.FileField(upload_to='')),
                ('acknowledged', models.BooleanField(default=False)),
                ('high_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_applicant.school')),
            ],
            bases=('base_applicant.application',),
        ),
    ]
