# Generated by Django 3.2.12 on 2022-02-12 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_applicant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicFundingApplication',
            fields=[
                ('application_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_applicant.application')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=40)),
                ('role', models.CharField(choices=[('Principal', 'Principal'), ('Principal_Assistant', 'Principal Assistant or Main Office Mgr'), ('Assistant', 'Assistant Principal'), ('Educator', 'Educator')], max_length=20)),
                ('department', models.CharField(max_length=50)),
                ('viability_and_usability', models.BooleanField()),
                ('emergency_services', models.BooleanField()),
                ('medical_needs', models.BooleanField()),
                ('internet_needs', models.BooleanField()),
                ('academic_needs', models.CharField(choices=[('Fees', 'Class Fees'), ('Technology', 'Technology'), ('Supplies', 'Supplies'), ('Transportation', 'Transportation Expenses'), ('Music', 'Music instrument rentals/repair'), ('Material', 'Classroom materials or curriculum'), ('Support', 'Academic Support'), ('Other', 'Other')], max_length=30)),
                ('needs_assistance', models.TextField(max_length=100)),
                ('funding_for', models.TextField(max_length=100)),
                ('funding_need', models.TextField(max_length=100)),
                ('funding_amount', models.CharField(max_length=100)),
                ('students_impacted', models.CharField(max_length=100)),
                ('agreement', models.BooleanField()),
            ],
            bases=('base_applicant.application',),
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('application_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_applicant.application')),
                ('statement', models.FileField(upload_to='')),
                ('transcript', models.FileField(upload_to='')),
                ('recommendation_letter_1', models.FileField(upload_to='')),
                ('recommendation_letter_2', models.FileField(upload_to='')),
                ('acknowledged', models.BooleanField(default=False)),
                ('high_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_applicant.school')),
            ],
            bases=('base_applicant.application',),
        ),
    ]
