# Generated by Django 3.2.11 on 2022-02-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='high_school',
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='address',
            field=models.CharField(default='No Address Given', max_length=300),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='email_address',
            field=models.EmailField(default='No Email Given', max_length=100),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='first_name',
            field=models.CharField(default='No First Name Given', max_length=100),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='last_name',
            field=models.CharField(default='No Last Name Given', max_length=100),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='phone_number',
            field=models.CharField(default='000-000-0000', max_length=20),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='school_choice',
            field=models.CharField(choices=[('S0', 'School 0'), ('S1', 'School 1'), ('S2', 'School 2'), ('S3', 'School 3')], default='SCHOOL0', max_length=2),
        ),
    ]
